### ISSUE TITLE
[Bug]: The Game updated

### ISSUE THREAD

**Issue by bilalbasem** [Mr-X-GTA/YimMenu#20]
### Describe the bug

The game updated the menu need an update thx

### Steps To Reproduce

The game updated the menu need an update thx

### Expected Behavior

The game updated the menu need an update thx

### Logs

The game updated the menu need an update thx

### Screenshots / Video

The game updated the menu need an update thx

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

The game updated the menu need an update thx

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rexsell** [comment]
proove, injecting with xenos makes game to crash and message window appeares

**Comment by Tessio** [comment]
Wait to merge #21

**Comment by bilalbasem** [comment]
whats the point of relaeseing a new dll when it still not working in public session. or is it working? i tried still crash when legit player join

**Comment by creenl1** [comment]
Not work in open lobby

**Comment by creenl1** [comment]
> > Beachten Sie, dass Sie FSL verwenden und der Sitzungshost sein müssen

I used it without fsl and was able to successfully host a session myself. I just can't join another session that someone else is hosting.. I always get a desync kick
