### ISSUE TITLE
[Bug]: Unable to enter online mode

### ISSUE THREAD

**Issue by huangmo-191** [Mr-X-GTA/YimMenu#34]
### Describe the bug

When using FSL+YimMenu, the following figure appears
![c604b2da1083e9ccf7ec2b5bdee8508f](https://github.com/user-attachments/assets/3e702df2-8995-45e5-99ed-76dd68e24a4a)

## Case 1
1. Put version.dll
2. Enter online mode
3. Enter successfully, but crash after a while

## Case 2
1. Put version.dll
2. Start the game
3. Inject YimMenu
4. Join online mode or new public in menu
5. The following picture appears
![c604b2da1083e9ccf7ec2b5bdee8508f](https://github.com/user-attachments/assets/3e702df2-8995-45e5-99ed-76dd68e24a4a)

### Expected Behavior

none

### Logs

none

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [x] I've tested this without co-loading anything.

**Comment by SourceModzZ** [comment]
Did you put the version.dll correctly in the GTA folder?

**Comment by SourceModzZ** [comment]
Did you put the version.dll correctly in the GTA folder?

**Comment by huangmo-191** [comment]
I found that it was injecting YIMMenu too early, thank you all, I have solved it
