### ISSUE TITLE
[Improvement]: Altering WASTED text at will

### ISSUE THREAD

**Issue by Deadlineem** [Mr-X-GTA/YimMenu#38]
### Which feature

Title speaks for itself, the message that shows when you die (with godmode) would be better if it can be altered to whatever we want it to say instead of being preset

### Reason

the "Dying with godmode, how?" text is a bit outdated at this point lol
![Screenshot_354](https://github.com/user-attachments/assets/59e93039-805d-4e34-8b13-539b6381926b)

**Comment by L7NEG** [comment]
> ### Which feature
> Title speaks for itself, the message that shows when you die (with godmode) would be better if it can be altered to whatever we want it to say instead of being preset
> 
> ### Reason
> the "Dying with godmode, how?" text is a bit outdated at this point lol ![Screenshot_354](https://private-user-images.githubusercontent.com/24372625/386878206-59e93039-805d-4e34-8b13-539b6381926b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDEyMTMsIm5iZiI6MTczMTg0MDkxMywicGF0aCI6Ii8yNDM3MjYyNS8zODY4NzgyMDYtNTllOTMwMzktODA1ZC00ZTM0LThiMTMtNTM5YjYzODE5MjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDEwNTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MDUxZjZjNWJkYjA4YjFjNWY3MTQzMGQ5Y2NhM2M3YWZkYjMxNGNlMjI1M2E0NmJjYzlkODA0MTRiOGU4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SHiaY8s0_FeXOXDienXG333MoIyMxWKo-kB5Qtuba0o)
> 
> ### Additional context
> _No response_

you can just open a pull request bro
