### ISSUE TITLE
[Bug]: Player tracking doesnt work

### ISSUE THREAD

**Issue by ghost** [Mr-X-GTA/YimMenu#4]
### Describe the bug

is it just me that the player tracking function stopped working? apparently they messed something up in scapi or what? this happens after they added BE

### Steps To Reproduce

1. Enable player tracking and wait a minute(or click the button Update online status of players or whatever)
2. Unknown status for all

### Expected Behavior

The players we track must be online or offline

### Logs

What is logs?

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I know this is an unofficial fork but maybe someone will write something smart in the comments about why this might not work

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by L7NEG** [comment]
Same

**Comment by L7NEG** [comment]
as cringe-arab said it works smoothly fr

**Comment by L7NEG** [comment]
oh

**Comment by L7NEG** [comment]
> @Cringe-Arab Can you test #10?

i can test it rn but it is still building

**Comment by L7NEG** [comment]
the build is done now im going to test it

**Comment by L7NEG** [comment]
> @Cringe-Arab Can you test #10?

it works now 
![Screenshot 2024-09-30 013724](https://github.com/user-attachments/assets/f9bbfdb9-195e-4431-a133-d15b5b6434cd)

**Comment by L7NEG** [comment]
lol i got desynced by a modder here it is 
![image](https://github.com/user-attachments/assets/b5aea3f0-9e32-4665-98ad-331ce40cadc2)

**Comment by L7NEG** [comment]
> > it works now
> 
> You need to track more than 32 players to test it

alright
i will add more rq

**Comment by L7NEG** [comment]
> > > it works now
> > 
> > 
> > You need to track more than 32 players to test it
> 
> alright i will add more rq

![Screenshot 2024-09-30 021310](https://github.com/user-attachments/assets/e6f13a0f-7adf-4ac7-b11e-91dc6dcfff4f)

overall 40 players in the player db and it works

**Comment by L7NEG** [comment]
> > overall 40 players in the player db and it works
> 
> Have you tested tracking more than 32 players that are online and checked that they are all displayed as online?

yes fr i just checked it and it works and i can join the players in the public lobbies without any problems but some i cant cuz a modder in the session desyncs me sometimes
