### ISSUE TITLE
[Bug]: Issues getting personal vehicle 

### ISSUE THREAD

**Issue by Ruabc123** [Mr-X-GTA/YimMenu#6]
### Describe the bug

I cant tp into, bring, or spawn PV it says mechanic is not ready or something, but i go and call the mecahnic normally and all is fine.

### Steps To Reproduce

Go to vehicle tab
Hit any of the listed options above
Mecahanic is not ready to deliver right now
Open phone call mechanic car comes fine

### Expected Behavior

I spawn my car and tp into it

### Logs

[cout.txt](https://github.com/user-attachments/files/17177238/cout.txt)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler

**Comment by Ruabc123** [comment]
new update fixed it, i assume it was the globals were outdated
