### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mirataen** [Mr-X-GTA/YimMenu#65]
### Describe the bug

Joining public sessions makes game crash! Menu takes longer and cache download keeps showing in log!

### Steps To Reproduce

Inject
Wait
Join 
Error

### Expected Behavior

Fix

### Logs

Can’t copy logs!

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by MoTastisch** [comment]
What was the solution? Having same issue...

**Comment by mirataen** [comment]
Remove old FSL. Disable battle and have -nobattleeye in steam advanced games settings. Launch, wait for pick story or online and join solo or invite. Public session still crashes as of now for me!

**Comment by MoTastisch** [comment]
thank you. What abt friend only session?

**Comment by mirataen** [comment]
> thank you. What abt friend only session?

Haven't tested but try and let me know if you get crash and it freezes and closes...

**Comment by MoTastisch** [comment]
Yes, it crashes on join of a player in a friend only session in online or when a player follows your invite in a invite only online session. I've opened an issue on this exact topic: https://github.com/Mr-X-GTA/YimMenu/issues/66

**Comment by mirataen** [comment]
> Yes, it crashes on join of a player in a friend only session in online or when a player follows your invite in a invite only online session. I've opened an issue on this exact topic: https://github.com/Mr-X-GTA/YimMenu/issues/66

Kool. Update otw plus the FSL download will drop soon. Waiting on UKC and Mr. X 💯🙏🏽

**Comment by Deadlineem** [comment]
> Yes, it crashes on join of a player in a friend only session in online or when a player follows your invite in a invite only online session. I've opened an issue on this exact topic: #66

You cannot play online with other players, only by yourself until FSL drops.  This is because FSL restores destroyed sync functions used by Battleye when you are not on a legit battleye-enabled client.  Unless we manage to restore said destroyed sync functions, the menu's wont allow online play with others.

**Comment by MoTastisch** [comment]
Okay thank you for clarification. I will close my issue then...

**Comment by MoTastisch** [comment]
Fixed as of 16.12.2024:
co-load FSL service with Yim
https://www.unknowncheats.me/forum/grand-theft-auto-v/616977-fsl-local-gtao-saves.html
